/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package randomJapanLocationer;

import java.util.Random;

public class JapanPrefectureMaker {
	private Prefecture prefecture;

	public JapanPrefectureMaker() {
		this(new Random().nextInt(46) + 1);
	}

	public JapanPrefectureMaker(int n) {
		this.prefecture = Prefecture.getPrefecture(n);
	}

	public String getPrefectureName() {
		return prefecture.getPrefectureName();
	}

	public String getPrefectureNumberString() {
		return prefecture.getPrefectureNumberString();
	}

	public int getPrefectureNumber() {
		return prefecture.getPrefectureNumber();
	}
}