/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package randomJapanLocationer;

import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;

import org.junit.Test;

public class JapanPrefectureMakerTest {
    @Test
    public void test() {
        JapanPrefectureMaker test1 = new JapanPrefectureMaker();
        JapanPrefectureMaker test2 = new JapanPrefectureMaker(47);

        System.out.println(test1.getPrefectureNumberString() + test1.getPrefectureName());

        assertThat(test2.getPrefectureName(), is("沖縄県"));
        assertThat(test2.getPrefectureNumberString(), is("47"));
    }
}
